name: Build and test

on:
  push:
    branches:
      - "main"
      - "staging"

  pull_request:
    branches:
      - "*"
env:
  PROGRAM_NAME: taxi

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          # This is x86
          - macos-13
          # This is arm
          - macos-14
          - ubuntu-20.04
        ocaml-compiler:
          - 5.2.1

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          cache-prefix: v1-${{ matrix.os }}
          opam-local-packages: taxi.opam

      - run: opam install ./taxi.opam --deps-only --with-doc --with-test

      - name: Check dev profile
        run: |
          opam exec -- make clean
          opam exec -- make build_dev
          opam exec -- make test_dev
          opam exec -- make install_dev

      - name: Send coverage
        run: |
          opam install bisect_ppx
          opam exec -- make send_coverage
        if: matrix.ocaml-compiler == '5.2.1' && matrix.os == 'ubuntu-20.04'
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check release profile
        run: |
          opam exec -- make clean
          opam exec -- make build_release
          opam exec -- make test_release
          opam exec -- make install_release

      - name: Upload taxi artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PROGRAM_NAME }}-${{ matrix.os }}
          path: _build/install/default/bin/${{ env.PROGRAM_NAME }}
        if: matrix.ocaml-compiler == '5.2.1'
